#!/usr/bin/env python3
"""
diffGenerated.py - compare the code GENERATED by two asn1scc builds.

The regression suite (runTests.py / regression) answers "does the generated
code still work?". This tool answers the complementary question a PR review
needs: "did the generated code CHANGE?". It enumerates the same test cases as
runTests.py (the --TCLS / --TCFS / --TCLFC / ... directives inside the
test-cases/acn corpus), invokes a baseline compiler (e.g. built from master)
and a candidate compiler (e.g. built from a PR head) with the regression
runner's flags, and diffs the generated output file by file.

Renames, API changes and silent semantic changes are invisible to the
regression suite by design (it regenerates and recompiles everything from
scratch); they show up immediately here.

Usage:
    diffGenerated.py --baseline <path/to/asn1scc> --candidate <path/to/asn1scc>
                     [--corpus <dir>] [-t <dir-or-file>] [--configs c-ws4,...]
                     [-j N] [-o <report-dir>]

Configs (default: all of them):
    c-ws4  c-ws8  c-ws8-slim  Ada-ws4  Ada-ws8      (legacy ACN)
    c-ws4-v2  c-ws8-v2  Ada-ws4-v2  Ada-ws8-v2      (--acn-v2)

Exit codes: 0 = no differences, 1 = differences found, 2 = tool error.

Notes:
  * Only code generation is exercised (no gcc/gnat/make), so a full run over
    the whole corpus takes minutes, not hours.
  * Trailing whitespace and CRLF/LF differences are ignored. Absolute output
    paths, if a generated file ever embeds one, are normalised to <OUT>.
  * Expected-to-fail cases (--TCLFC/--TCFFC) are run through both compilers
    and their (normalised) error messages are compared instead.
  * Identical outputs are deleted as soon as they are compared; only the
    differing work directories are kept for inspection.
"""

import argparse
import concurrent.futures
import difflib
import hashlib
import os
import re
import shutil
import subprocess
import sys
import threading
from collections import defaultdict

ACN_HEADER = "-- Auto generated file\n\nTEST-CASE DEFINITIONS ::= BEGIN\n"
ACN_FOOTER = "END\n"

# directive -> (acn source, expected outcome)
#   acn source: "inline" (body follows the directive) or "file" (filename follows)
#   outcome:    "ok"   generation must succeed
#               "cerr" generation must fail in the compiler
DIRECTIVES = [
    ("--TCLS",  "inline", "ok"),
    ("--TCLFC", "inline", "cerr"),
    ("--TCLFE", "inline", "ok"),    # fails at run time; generation succeeds
    ("--TCFS",  "file",   "ok"),
    ("--TCFFC", "file",   "cerr"),
    ("--TCFFE", "file",   "ok"),
]

COMPARE_EXCLUDE = {"ast.xml"}

DEFAULT_CONFIGS = [
    "c-ws4", "c-ws8", "c-ws8-slim", "Ada-ws4", "Ada-ws8",
    "c-ws4-v2", "c-ws8-v2", "Ada-ws4-v2", "Ada-ws8-v2",
]


class Config:
    def __init__(self, name):
        self.name = name
        parts = name.split("-")
        self.lang = parts[0]            # "c" or "Ada"
        self.ws = int(parts[1][2:])     # ws4 / ws8
        self.slim = "slim" in parts
        self.acnv2 = "v2" in parts
        if self.lang not in ("c", "Ada"):
            raise ValueError("unsupported language in config " + name)
        if self.slim and self.lang != "c":
            raise ValueError("slim mode is C-only: " + name)

    def compiler_args(self):
        args = ["-" + self.lang, "-x", "ast.xml", "-uPER", "-ACN",
                "-typePrefix", "ASN1SCC_", "-renamePolicy", "3",
                "-fp", "AUTO", "-equal", "-atc",
                "-fpWordSize", str(self.ws), "-wordSize", str(self.ws)]
        if self.slim:
            args.append("-slim")
        if self.acnv2:
            args.append("--acn-v2")
        if self.lang == "Ada" and self.ws == 4:
            args += ["-t", "msp430"]
        return args


class Case:
    """One test-case directive of one .asn1 file."""
    def __init__(self, rel_id, asn1_path, acn_content, outcome):
        self.rel_id = rel_id            # e.g. "09-CHOICE/014.asn1#3-TCFS"
        self.asn1_path = asn1_path
        self.acn_content = acn_content
        self.outcome = outcome


def enumerate_cases(corpus_root, selector):
    """Yield Case objects, mirroring runTests.py's directive parsing."""
    if selector and os.path.isfile(selector):
        asn1_files = [os.path.abspath(selector)]
    else:
        top = os.path.abspath(selector) if selector else corpus_root
        asn1_files = []
        for cur, _dirs, files in sorted(os.walk(top)):
            for f in sorted(files):
                if f.endswith(".asn1"):
                    asn1_files.append(os.path.join(cur, f))
    for asn1_path in asn1_files:
        rel = os.path.relpath(asn1_path, corpus_root)
        case_dir = os.path.dirname(asn1_path)
        with open(asn1_path, "r", errors="replace") as f:
            lines = f.readlines()
        idx = 0
        stop = False
        for line in lines:
            if stop:
                break
            if line.startswith("--TCBREAK"):
                stop = True
                continue
            for tag, source, outcome in DIRECTIVES:
                if not line.startswith(tag):
                    continue
                # longer tags first would be cleaner, but the runner does the
                # same prefix test, and TCLS/TCLFC etc. are prefix-free among
                # the lines that actually occur (TCLS lines never start with
                # TCLF...), so mirror it and match the first tag that fits.
                payload = line[len(tag):].strip()
                if outcome == "cerr":
                    payload = payload.split("$$$")[0].strip()
                if source == "inline":
                    acn = ACN_HEADER + "\t" + payload + "\n" + ACN_FOOTER
                else:
                    with open(os.path.join(case_dir, payload), "r",
                              errors="replace") as af:
                        acn = af.read()
                idx += 1
                yield Case("%s#%d-%s" % (rel, idx, tag[2:]),
                           asn1_path, acn, outcome)
                break


def normalize_text(data, out_dirs):
    text = data.replace("\r\n", "\n")
    for d in out_dirs:
        text = text.replace(d + os.sep, "<OUT>/").replace(d, "<OUT>")
    lines = [ln.rstrip() for ln in text.split("\n")]
    return "\n".join(lines)


def run_compiler(compiler, cfg, case, workdir):
    os.makedirs(workdir, exist_ok=True)
    asn1 = os.path.join(workdir, "sample1.asn1")
    acn = os.path.join(workdir, "sample1.acn")
    shutil.copyfile(case.asn1_path, asn1)
    with open(acn, "w") as f:
        f.write(case.acn_content)
    cmd = [compiler] + cfg.compiler_args() + \
          ["-o", workdir, "sample1.asn1", "sample1.acn"]
    try:
        p = subprocess.run(cmd, cwd=workdir, capture_output=True,
                           text=True, timeout=300)
        return p.returncode, p.stderr
    except subprocess.TimeoutExpired:
        return -1, "TIMEOUT after 300s"


def list_generated(workdir):
    out = {}
    for cur, _dirs, files in os.walk(workdir):
        for f in files:
            if f in COMPARE_EXCLUDE or f in ("sample1.asn1", "sample1.acn"):
                continue
            full = os.path.join(cur, f)
            out[os.path.relpath(full, workdir)] = full
    return out


class Finding:
    def __init__(self, kind, cfg, case, relpath, detail):
        self.kind = kind        # missing-file / extra-file / content /
                                # rc-mismatch / stderr-drift
        self.cfg = cfg
        self.case = case
        self.relpath = relpath
        self.detail = detail    # unified diff text or message

    def signature(self):
        # position-independent digest so the same change in many cases
        # collapses into one report entry
        body = "\n".join(l for l in self.detail.split("\n")
                         if not l.startswith("@@"))
        h = hashlib.sha256((self.kind + "|" + self.relpath + "|" +
                            body).encode()).hexdigest()[:12]
        return h


def compare_case(baseline, candidate, cfg, case, workroot, keep):
    """Returns a list of Findings for one (case, config)."""
    tag = re.sub(r"[^A-Za-z0-9._-]", "_", case.rel_id)
    wd_base = os.path.join(workroot, cfg.name, tag, "base")
    wd_cand = os.path.join(workroot, cfg.name, tag, "cand")
    rc_b, err_b = run_compiler(baseline, cfg, case, wd_base)
    rc_c, err_c = run_compiler(candidate, cfg, case, wd_cand)
    findings = []
    out_dirs = [wd_base, wd_cand]
    if (rc_b == 0) != (rc_c == 0):
        findings.append(Finding(
            "rc-mismatch", cfg, case, "(compiler exit)",
            "baseline rc=%d, candidate rc=%d\nbaseline stderr:\n%s\n"
            "candidate stderr:\n%s" %
            (rc_b, rc_c, normalize_text(err_b, out_dirs),
             normalize_text(err_c, out_dirs))))
    elif rc_b != 0:
        nb = normalize_text(err_b, out_dirs)
        nc = normalize_text(err_c, out_dirs)
        if nb != nc:
            findings.append(Finding(
                "stderr-drift", cfg, case, "(compiler stderr)",
                "\n".join(difflib.unified_diff(
                    nb.split("\n"), nc.split("\n"),
                    "baseline stderr", "candidate stderr", lineterm=""))))
    else:
        files_b = list_generated(wd_base)
        files_c = list_generated(wd_cand)
        for rel in sorted(set(files_b) - set(files_c)):
            findings.append(Finding("missing-file", cfg, case, rel,
                                    "generated by baseline only"))
        for rel in sorted(set(files_c) - set(files_b)):
            findings.append(Finding("extra-file", cfg, case, rel,
                                    "generated by candidate only"))
        for rel in sorted(set(files_b) & set(files_c)):
            with open(files_b[rel], "r", errors="replace") as f:
                tb = normalize_text(f.read(), out_dirs)
            with open(files_c[rel], "r", errors="replace") as f:
                tc = normalize_text(f.read(), out_dirs)
            if tb != tc:
                diff = "\n".join(difflib.unified_diff(
                    tb.split("\n"), tc.split("\n"),
                    "baseline/" + rel, "candidate/" + rel, lineterm=""))
                findings.append(Finding("content", cfg, case, rel, diff))
    if not findings and not keep:
        shutil.rmtree(os.path.join(workroot, cfg.name, tag),
                      ignore_errors=True)
    return findings


def main():
    ap = argparse.ArgumentParser(
        description="Diff the generated code of two asn1scc builds over the "
                    "v4Tests corpus.")
    ap.add_argument("--baseline", required=True,
                    help="asn1scc executable of the reference build (master)")
    ap.add_argument("--candidate", required=True,
                    help="asn1scc executable of the build under review (PR)")
    ap.add_argument("--corpus", default=None,
                    help="corpus root (default: <script>/../test-cases/acn)")
    ap.add_argument("-t", "--testCaseSet", default=None,
                    help="restrict to one .asn1 file or one directory")
    ap.add_argument("--configs", default=",".join(DEFAULT_CONFIGS),
                    help="comma-separated configs (default: %(default)s)")
    ap.add_argument("-j", "--jobs", type=int, default=os.cpu_count() or 4)
    ap.add_argument("-o", "--out", default="diff-generated-report",
                    help="report directory (default: %(default)s)")
    ap.add_argument("--keep-identical", action="store_true",
                    help="keep work dirs even when outputs are identical")
    args = ap.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))
    corpus = os.path.abspath(args.corpus) if args.corpus else \
        os.path.abspath(os.path.join(script_dir, "..", "test-cases", "acn"))
    baseline = os.path.abspath(args.baseline)
    candidate = os.path.abspath(args.candidate)
    for exe in (baseline, candidate):
        if not os.path.exists(exe):
            print("compiler not found:", exe, file=sys.stderr)
            return 2
    try:
        configs = [Config(c) for c in args.configs.split(",") if c]
    except ValueError as e:
        print("bad config:", e, file=sys.stderr)
        return 2

    out_dir = os.path.abspath(args.out)
    workroot = os.path.join(out_dir, "work")
    diffs_dir = os.path.join(out_dir, "diffs")
    shutil.rmtree(out_dir, ignore_errors=True)
    os.makedirs(workroot)
    os.makedirs(diffs_dir)

    cases = list(enumerate_cases(corpus, args.testCaseSet))
    if not cases:
        print("no test cases found under", corpus, file=sys.stderr)
        return 2
    units = [(cfg, case) for cfg in configs for case in cases]
    print("%d cases x %d configs = %d comparisons, %d jobs" %
          (len(cases), len(configs), len(units), args.jobs))

    all_findings = []
    stats = defaultdict(lambda: [0, 0])   # cfg.name -> [compared, differing]
    lock = threading.Lock()
    done = [0]

    def work(unit):
        cfg, case = unit
        f = compare_case(baseline, candidate, cfg, case, workroot,
                         args.keep_identical)
        with lock:
            stats[cfg.name][0] += 1
            if f:
                stats[cfg.name][1] += 1
                all_findings.extend(f)
            done[0] += 1
            if done[0] % 200 == 0:
                print("  %d/%d done, %d finding(s) so far" %
                      (done[0], len(units), len(all_findings)))

    with concurrent.futures.ThreadPoolExecutor(args.jobs) as ex:
        list(ex.map(work, units))

    # group findings by signature
    groups = defaultdict(list)
    for f in all_findings:
        groups[f.signature()].append(f)

    report = os.path.join(out_dir, "report.md")
    with open(report, "w") as r:
        r.write("# Generated-code diff report\n\n")
        r.write("baseline:  %s\ncandidate: %s\ncorpus:    %s\n\n" %
                (baseline, candidate, corpus))
        r.write("| config | cases compared | cases with differences |\n")
        r.write("|---|---|---|\n")
        for cfg in configs:
            c, d = stats[cfg.name]
            r.write("| %s | %d | %d |\n" % (cfg.name, c, d))
        r.write("\n%d finding(s) in %d unique signature(s)\n\n" %
                (len(all_findings), len(groups)))
        for i, (sig, fs) in enumerate(
                sorted(groups.items(), key=lambda kv: -len(kv[1])), 1):
            f0 = fs[0]
            cfgs = sorted({f.cfg.name for f in fs})
            examples = sorted({f.case.rel_id for f in fs})[:3]
            diff_file = os.path.join(diffs_dir, "sig-%02d-%s.diff" % (i, sig))
            with open(diff_file, "w") as df:
                df.write(f0.detail + "\n")
            r.write("## %d. [%s] %s  (x%d)\n\n" %
                    (i, f0.kind, f0.relpath, len(fs)))
            r.write("- configs: %s\n" % ", ".join(cfgs))
            r.write("- example cases: %s\n" % ", ".join(examples))
            r.write("- diff: diffs/%s\n\n" % os.path.basename(diff_file))
            preview = "\n".join(f0.detail.split("\n")[:20])
            r.write("```diff\n%s\n```\n\n" % preview)

    print()
    for cfg in configs:
        c, d = stats[cfg.name]
        print("%-12s %4d compared, %4d with differences" % (cfg.name, c, d))
    print("\n%d finding(s), %d unique signature(s)" %
          (len(all_findings), len(groups)))
    print("report:", report)
    return 1 if all_findings else 0


if __name__ == "__main__":
    sys.exit(main())
