#!/bin/bash

set -e -u -o pipefail

ASN1SCC_LANG="${1:-python}"

case "$ASN1SCC_LANG" in
    c|Ada|Scala|python)
        echo "Generating output for language $ASN1SCC_LANG"
        ;;
    *)
        echo "Error: invalid language '$ASN1SCC_LANG'. Must be one of: c, Ada, Scala, python." >&2
        exit 1
        ;;
esac

BASE_OUT_DIR="generated-$ASN1SCC_LANG-output"
echo "Removing generated .stg.fs files & python-output..."
rm -f -- StgPython/*.stg.fs
#rm -r $OUT_DIR

dotnet build asn1scc

echo "Generating new .stg.fs files..."
cd StgPython && dotnet ../parseStg2/bin/Debug/net9.0/parseStg2.dll backends.xml 3 && cd ..

ASN1_FILES="./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/additional-test-cases/NULLTERMINATED.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/ccsds/PacketTypes.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/ccsds/TC-Packet.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/ccsds/TC-Payload.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/ApplicationProcess.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/ApplicationProcessUser.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/BasicTypes.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/DiagnosticParameterReportStructure.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/Dummy.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/EventDefinition.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/ExecutionStep.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/FilePath.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/HousekeepingParameterReportStructure.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/MessageType.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/Parameter.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/Request.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/SpacecraftTimeReferenceStatus.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/TimeWindow.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/ErrorCodes.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-10.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-5.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-6.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-7.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-8.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/VerificationRequest.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/LogicalDevice.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PhysicalDevice.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-10.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-11.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-12.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-5.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-6.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-7.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-8.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-9.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/Registers.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/Transaction.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/CollectionInterval.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/ParameterFunctionalReportingDefinition.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/ParameterReportingEntries.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/ParameterReportStructureType.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PeriodicGenerationActionStatus.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PeriodicGenerationProperties.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-10.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-11.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-12.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-25.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-26.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-27.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-28.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-29.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-30.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-31.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-32.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-33.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-34.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-35.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-36.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-37.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-38.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-39.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-40.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-41.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-42.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-43.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-44.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-5.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-6.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-7.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-8.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-9.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/Intervals.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/ParameterStatisticsDefinitions.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-5.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-6.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-7.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-8.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-9.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-5.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-6.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-7.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-8.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/Data.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/Memory.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-10.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-11.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-12.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-13.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-14.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-15.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-16.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-17.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-18.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-19.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-20.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-21.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-22.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-5.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-6.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-7.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-8.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-9.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/RawMemory.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/StructuredMemory.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-08/PUS-8-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-09/PUS-9-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-09/PUS-9-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-09/PUS-9-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-09/RateExponentialValue.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/Group.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-10.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-11.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-12.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-13.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-14.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-15.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-16.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-17.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-18.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-19.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-20.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-21.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-22.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-23.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-24.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-25.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-26.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-27.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-5.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-6.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-7.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-8.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-9.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/SubSchedule.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/CheckValidityCondition.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/FMON.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/ParameterMonitoringDefinition.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PMON.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PMON-FailingNumber.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-10.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-13.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-14.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-15.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-16.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-17.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-18.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-19.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-20.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-21.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-22.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-23.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-24.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-25.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-26.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-27.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-28.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/LargePacketTransferMessageParts.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-10.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-11.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-16.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-9.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/ApplicationProcessForwardControl.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/DiagnosticParameterReportForwardControl.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/EventDefinitionForwardControl.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/HousekeepingParameterReportForwardControl.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-10.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-11.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-12.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-13.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-14.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-15.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-16.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-5.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-6.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-7.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-8.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-9.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/SubsamplingRate.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PacketStore.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PacketStoreConfiguration.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PacketStoreEnumerations.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-5.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-6.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-9.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-11.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-12.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-13.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-14.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-15.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-16.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-17.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-18.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-19.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-20.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-21.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-22.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-23.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-24.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-25.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-26.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-27.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-28.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-29.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-30.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-31.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-32.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-33.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-34.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-35.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-36.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-37.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-38.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-39.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-40.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/Storage-ControlConfiguration.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/Storage-ControlDiagnosticParameterReport.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/Storage-ControlEventReportBlocking.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/Storage-ControlHousekeepingParameterReport.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/Storage-ControlReportType.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-17/PUS-17-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-17/PUS-17-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-17/PUS-17-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-17/PUS-17-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/OBCP.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/OBCPActivation.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/OBCPArgumentValues.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/OBCPManagement.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/OBCPWithold.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-5.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-6.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-7.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-8.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-9.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-12.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-13.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-14.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-15.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-16.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-17.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-18.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-19.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-20.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-21.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-22.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/EventActionStatus.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/EventDefinitionSystem.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-1.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-10.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-11.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-2.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-3.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-4.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-5.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-6.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-7.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-8.asn1 \
            ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-9.asn1"

ACN_FILES="./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/additional-test-cases/NULLTERMINATED.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/ccsds/PacketTypes.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/ccsds/TC-Packet.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/ccsds/TC-Payload.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/ApplicationProcess.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/ApplicationProcessUser.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/BasicTypes.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/DiagnosticParameterReportStructure.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/Dummy.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/EventDefinition.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/ExecutionStep.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/FilePath.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/HousekeepingParameterReportStructure.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/MessageType.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/Parameter.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/Request.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/SpacecraftTimeReferenceStatus.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/common/TimeWindow.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/ErrorCodes.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-10.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-5.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-6.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-7.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/PUS-1-8.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-01/VerificationRequest.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/LogicalDevice.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PhysicalDevice.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-10.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-11.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-12.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-5.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-6.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-7.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-8.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/PUS-2-9.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/Registers.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-02/Transaction.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/CollectionInterval.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/ParameterFunctionalReportingDefinition.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/ParameterReportingEntries.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/ParameterReportStructureType.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PeriodicGenerationActionStatus.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PeriodicGenerationProperties.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-10.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-11.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-12.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-25.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-26.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-27.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-28.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-29.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-30.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-31.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-32.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-33.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-34.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-35.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-36.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-37.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-38.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-39.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-40.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-41.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-42.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-43.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-44.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-5.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-6.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-7.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-8.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-03/PUS-3-9.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/Intervals.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/ParameterStatisticsDefinitions.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-5.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-6.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-7.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-8.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-04/PUS-4-9.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-5.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-6.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-7.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-05/PUS-5-8.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/Data.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/Memory.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-10.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-11.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-12.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-13.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-14.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-15.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-16.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-17.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-18.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-19.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-20.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-21.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-22.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-5.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-6.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-7.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-8.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/PUS-6-9.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/RawMemory.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-06/StructuredMemory.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-08/PUS-8-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-09/PUS-9-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-09/PUS-9-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-09/PUS-9-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-09/RateExponentialValue.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/Group.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-10.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-11.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-12.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-13.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-14.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-15.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-16.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-17.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-18.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-19.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-20.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-21.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-22.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-23.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-24.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-25.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-26.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-27.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-5.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-6.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-7.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-8.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/PUS-11-9.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-11/SubSchedule.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/CheckValidityCondition.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/FMON.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/ParameterMonitoringDefinition.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PMON.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PMON-FailingNumber.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-10.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-13.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-14.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-15.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-16.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-17.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-18.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-19.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-20.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-21.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-22.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-23.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-24.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-25.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-26.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-27.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-28.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-12/PUS-12-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/LargePacketTransferMessageParts.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-10.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-11.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-16.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-13/PUS-13-9.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/ApplicationProcessForwardControl.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/DiagnosticParameterReportForwardControl.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/EventDefinitionForwardControl.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/HousekeepingParameterReportForwardControl.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-10.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-11.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-12.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-13.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-14.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-15.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-16.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-5.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-6.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-7.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-8.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/PUS-14-9.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-14/SubsamplingRate.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PacketStore.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PacketStoreConfiguration.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PacketStoreEnumerations.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-5.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-6.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-9.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-11.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-12.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-13.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-14.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-15.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-16.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-17.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-18.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-19.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-20.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-21.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-22.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-23.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-24.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-25.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-26.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-27.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-28.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-29.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-30.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-31.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-32.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-33.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-34.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-35.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-36.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-37.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-38.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-39.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/PUS-15-40.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/Storage-ControlDiagnosticParameterReport.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/Storage-ControlEventReportBlocking.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/Storage-ControlHousekeepingParameterReport.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-15/Storage-ControlReportType.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-17/PUS-17-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-17/PUS-17-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-17/PUS-17-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-17/PUS-17-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/OBCP.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/OBCPActivation.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/OBCPArgumentValues.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/OBCPManagement.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/OBCPWithold.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-5.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-6.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-7.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-8.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-9.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-12.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-13.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-14.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-15.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-16.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-17.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-18.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-19.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-20.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-21.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-18/PUS-18-22.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/EventActionStatus.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/EventDefinitionSystem.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-1.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-10.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-11.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-2.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-3.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-4.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-5.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-6.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-7.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-8.acn \
           ./PUSCScalaTest/asn1-pusc-lib-asn1CompilerTestInput/service-19/PUS-19-9.acn"

TESTLIB_FILES="./Asn1AcnTestLib/primitives/boolean/boolean-basic.asn1 \
               ./Asn1AcnTestLib/primitives/boolean/boolean-false-value.asn1 \
               ./Asn1AcnTestLib/primitives/boolean/boolean-false-value.acn \
               ./Asn1AcnTestLib/primitives/boolean/boolean-true-value.asn1 \
               ./Asn1AcnTestLib/primitives/boolean/boolean-true-value.acn \
               ./Asn1AcnTestLib/primitives/boolean/boolean-combined.asn1 \
               ./Asn1AcnTestLib/primitives/boolean/boolean-combined.acn \
               ./Asn1AcnTestLib/primitives/integer/integer-basic.asn1 \
               ./Asn1AcnTestLib/primitives/integer/integer-range-zero-start.asn1 \
               ./Asn1AcnTestLib/primitives/integer/integer-range-positive.asn1 \
               ./Asn1AcnTestLib/primitives/integer/integer-range-negative.asn1 \
               ./Asn1AcnTestLib/primitives/integer/integer-acn-size.asn1 \
               ./Asn1AcnTestLib/primitives/integer/integer-acn-size.acn \
               ./Asn1AcnTestLib/primitives/integer/integer-endianness-big.asn1 \
               ./Asn1AcnTestLib/primitives/integer/integer-endianness-big.acn \
               ./Asn1AcnTestLib/primitives/integer/integer-endianness-little.asn1 \
               ./Asn1AcnTestLib/primitives/integer/integer-endianness-little.acn \
               ./Asn1AcnTestLib/primitives/integer/integer-encoding-posint.asn1 \
               ./Asn1AcnTestLib/primitives/integer/integer-encoding-posint.acn \
               ./Asn1AcnTestLib/primitives/integer/integer-encoding-twoscomplement.asn1 \
               ./Asn1AcnTestLib/primitives/integer/integer-encoding-twoscomplement.acn \
               ./Asn1AcnTestLib/primitives/real/real-ieee754-32.asn1 \
               ./Asn1AcnTestLib/primitives/real/real-ieee754-32.acn \
               ./Asn1AcnTestLib/primitives/real/real-ieee754-64.asn1 \
               ./Asn1AcnTestLib/primitives/real/real-ieee754-64.acn \
               ./Asn1AcnTestLib/primitives/real/real-endianness-big.asn1 \
               ./Asn1AcnTestLib/primitives/real/real-endianness-big.acn \
               ./Asn1AcnTestLib/primitives/real/real-endianness-little.asn1 \
               ./Asn1AcnTestLib/primitives/real/real-endianness-little.acn \
               ./Asn1AcnTestLib/primitives/bitstring/bitstring-basic.asn1 \
               ./Asn1AcnTestLib/primitives/bitstring/bitstring-size-fixed.asn1 \
               ./Asn1AcnTestLib/primitives/bitstring/bitstring-size-range.asn1 \
               ./Asn1AcnTestLib/primitives/bitstring/bitstring-acn-size.asn1 \
               ./Asn1AcnTestLib/primitives/bitstring/bitstring-acn-size.acn \
               ./Asn1AcnTestLib/primitives/octetstring/octetstring-basic.asn1 \
               ./Asn1AcnTestLib/primitives/octetstring/octetstring-size-fixed.asn1 \
               ./Asn1AcnTestLib/primitives/octetstring/octetstring-size-range.asn1 \
               ./Asn1AcnTestLib/primitives/octetstring/octetstring-acn-size.asn1 \
               ./Asn1AcnTestLib/primitives/octetstring/octetstring-acn-size.acn \
               ./Asn1AcnTestLib/primitives/ia5string/ia5string-basic.asn1 \
               ./Asn1AcnTestLib/primitives/ia5string/ia5string-size-fixed.asn1 \
               ./Asn1AcnTestLib/primitives/ia5string/ia5string-size-range.asn1 \
               ./Asn1AcnTestLib/primitives/enumerated/enumerated-basic.asn1 \
               ./Asn1AcnTestLib/primitives/enumerated/enumerated-acn-size.asn1 \
               ./Asn1AcnTestLib/primitives/enumerated/enumerated-acn-size.acn \
               ./Asn1AcnTestLib/primitives/enumerated/enumerated-encode-values.asn1 \
               ./Asn1AcnTestLib/primitives/enumerated/enumerated-encode-values.acn \
               ./Asn1AcnTestLib/primitives/null/null-basic.asn1 \
               ./Asn1AcnTestLib/structured/sequence/sequence-basic.asn1 \
               ./Asn1AcnTestLib/structured/sequence/sequence-optional.asn1 \
               ./Asn1AcnTestLib/structured/sequence/sequence-default.asn1 \
               ./Asn1AcnTestLib/structured/sequence-of/sequence-of-basic.asn1 \
               ./Asn1AcnTestLib/structured/sequence-of/sequence-of-size-fixed.asn1 \
               ./Asn1AcnTestLib/structured/sequence-of/sequence-of-size-range.asn1 \
               ./Asn1AcnTestLib/structured/sequence-of/sequence-of-acn-size.asn1 \
               ./Asn1AcnTestLib/structured/sequence-of/sequence-of-acn-size.acn \
               ./Asn1AcnTestLib/structured/choice/choice-basic.asn1 \
               ./Asn1AcnTestLib/structured/choice/choice-determinant.asn1 \
               ./Asn1AcnTestLib/structured/choice/choice-determinant.acn \
               ./Asn1AcnTestLib/advanced/subtyping/subtyping-value-constraints.asn1 \
               ./Asn1AcnTestLib/advanced/subtyping/subtyping-with-components.asn1 \
               ./Asn1AcnTestLib/advanced/subtyping/subtyping-nested.asn1 \
               ./Asn1AcnTestLib/advanced/subtyping/subtyping-pattern.asn1 \
               ./Asn1AcnTestLib/advanced/parameterized/parameterized-basic.asn1 \
               ./Asn1AcnTestLib/advanced/parameterized/parameterized-complex.asn1 \
               ./Asn1AcnTestLib/advanced/imports/imports-base-types.asn1 \
               ./Asn1AcnTestLib/advanced/imports/imports-extended-types.asn1 \
               ./Asn1AcnTestLib/advanced/imports/imports-user-module.asn1 \
               ./Asn1AcnTestLib/advanced/imports/imports-multi-module.asn1 \
               ./Asn1AcnTestLib/advanced/nested/nested-acn-basic.asn1 \
               ./Asn1AcnTestLib/advanced/nested/nested-acn-basic.acn \
               ./Asn1AcnTestLib/advanced/nested/nested-acn-parametrization.asn1 \
               ./Asn1AcnTestLib/advanced/nested/nested-acn-parametrization.acn \
               ./Asn1AcnTestLib/advanced/nested/nested-acn-conditional.asn1 \
               ./Asn1AcnTestLib/advanced/nested/nested-acn-conditional.acn \
               ./Asn1AcnTestLib/acn-attributes/alignment/alignment-byte.asn1 \
               ./Asn1AcnTestLib/acn-attributes/alignment/alignment-byte.acn \
               ./Asn1AcnTestLib/acn-attributes/alignment/alignment-word.asn1 \
               ./Asn1AcnTestLib/acn-attributes/alignment/alignment-word.acn \
               ./Asn1AcnTestLib/acn-attributes/present-when/present-when-sequence.asn1 \
               ./Asn1AcnTestLib/acn-attributes/present-when/present-when-sequence.acn \
               ./Asn1AcnTestLib/acn-attributes/present-when/present-when-choice.asn1 \
               ./Asn1AcnTestLib/acn-attributes/present-when/present-when-choice.acn \
               ./Asn1AcnTestLib/acn-attributes/save-position/save-position-basic.asn1 \
               ./Asn1AcnTestLib/acn-attributes/save-position/save-position-basic.acn \
               ./Asn1AcnTestLib/acn-attributes/save-position/save-position-complex.asn1 \
               ./Asn1AcnTestLib/acn-attributes/save-position/save-position-complex.acn \
               ./Asn1AcnTestLib/additional/determinant_color.asn1 \
               ./Asn1AcnTestLib/additional/determinant_color.acn"
              
DEBUG_FILES="./Asn1AcnTestLib/additional/deep-field-access.asn1 \
             ./Asn1AcnTestLib/additional/deep-field-access.acn \
             ./Asn1AcnTestLib/additional/determinant_color.asn1 \
             ./Asn1AcnTestLib/additional/determinant_color.acn \
             ./Asn1AcnTestLib/advanced/subtyping/subtyping-value-constraints.asn1"
          
                             
#TEMPLATE_INFO="-printTemplateInfo"
TEMPLATE_INFO=""
#PREFIX="ATELERIS"
PREFIX=""

echo "Running Asn1SCC Compiler for ASN1..."
./asn1scc/bin/Debug/net9.0/asn1scc "-$ASN1SCC_LANG" $TEMPLATE_INFO -uPER -atc -fp AUTO -typePrefix "$PREFIX" -o "$BASE_OUT_DIR/asn1_uper" $ASN1_FILES 

echo "Running Asn1SCC Compiler for TestLib..."
./asn1scc/bin/Debug/net9.0/asn1scc "-$ASN1SCC_LANG" $TEMPLATE_INFO -uPER -atc -fp AUTO -typePrefix "$PREFIX" -o "$BASE_OUT_DIR/testlib_uper" $TESTLIB_FILES


