all: build

build: dotnet-debian.SENTINEL
	dotnet build -c Debug Antlr/
	dotnet build -c Debug parseStg2/
	dotnet build -c Debug "asn1scc.sln"

publish: build
	dotnet publish -c Debug --self-contained true -r linux-x64  asn1scc.sln

publish-win64: build
	dotnet publish -c Debug --self-contained true -r win-x64  asn1scc.sln

dotnet-debian.SENTINEL:
	# install dotnet on debian (https://docs.microsoft.com/en-us/dotnet/core/install/linux-debian)
	wget --no-check-certificate https://packages.microsoft.com/config/debian/13/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
	sudo dpkg -i packages-microsoft-prod.deb
	rm packages-microsoft-prod.deb
	# install the sdk
	sudo apt update
	sudo apt install -y apt-transport-https &&  sudo apt update &&  sudo apt install -y dotnet-sdk-10.0
	touch $@

tests:
	$(MAKE) -C v4Tests

clean:
	rm -rf asn1scc/bin packages-microsoft-prod.deb

distclean: clean
	rm dotnet-debian.SENTINEL

.PHONY: all tests clean
