"""
ASN.1 Python Runtime Library

This module provides ASN.1-specific types and operations for Python code generation.
Generated by asn1scc - the ASN.1 compiler of the European Space Agency (ESA).
"""

from .asn1_exceptions import (
    # Error handling
    Asn1SccError, Asn1Exception, Asn1InvalidValueException, Asn1OverflowException, Asn1ValueOutOfRangeException, Asn1UnexpectedEndOfDataException,
    
    # Testcase Errors
    Asn1TestcaseError, Asn1TestcaseEncodeFailedError, Asn1TestcaseDecodeFailedError, Asn1TestcaseConstraintFailedError, Asn1TestcaseDifferentResultError
)

from .asn1_types import (
    # ASN.1 semantic types
    Asn1Boolean, NullType, Real32, Asn1Base, Asn1ObjectIdentifier, OBJECT_IDENTIFIER_MAX_LENGTH,

    # Time types
    Asn1Date, Asn1LocalTime, Asn1UtcTime,
    Asn1TimeWithTimeZone, Asn1DateLocalTime,
    Asn1DateUtcTime, Asn1DateTimeWithTimeZone,

    # Constraint Validation
    Asn1ConstraintValidResult,
)

from .bitstream import BitStream, BitStreamError

from .codec import (
    Encoding, Codec, EncodeResult, DecodeResult, ErrorCode,
    ENCODE_OK, DECODE_OK, ERROR_INSUFFICIENT_DATA,
    ERROR_INVALID_VALUE, ERROR_CONSTRAINT_VIOLATION,
)

from .codec_uper import UPEREncoder, UPERDecoder
from .acn_encoder import ACNEncoder
from .acn_decoder import ACNDecoder
# from .codec_xer import XERCodec
# from .codec_ber import BERCodec
# from .codec_per import PERCodec

__version__ = "1.0.0"
__author__ = "ASN.1 SCC Team"
__description__ = "ASN.1 runtime library for Python"

__all__ = [
    # Types
    "Asn1Boolean", "NullType", "Real32", "Asn1ObjectIdentifier", "OBJECT_IDENTIFIER_MAX_LENGTH",
    "Asn1Date", "Asn1LocalTime", "Asn1UtcTime",
    "Asn1TimeWithTimeZone", "Asn1DateLocalTime",
    "Asn1DateUtcTime", "Asn1DateTimeWithTimeZone",
    
    # Base Class
    "Asn1Base",

    # Constraint Validation
    "Asn1ConstraintValidResult",
    
    # Errors
    "Asn1SccError", "Asn1Exception", "Asn1InvalidValueException", "Asn1OverflowException", "Asn1ValueOutOfRangeException", "Asn1UnexpectedEndOfDataException",

    # Testcase Errors
    "Asn1TestcaseError", "Asn1TestcaseEncodeFailedError", "Asn1TestcaseDecodeFailedError", "Asn1TestcaseConstraintFailedError", "Asn1TestcaseDifferentResultError",
    
    # Bitstream
    "BitStream", "BitStreamError",

    # Codecs
    "Encoding", "Codec", "EncodeResult", "DecodeResult", "ErrorCode",
    "ACNDecoder", "ACNEncoder", "UPERDecoder", "UPEREncoder", #"XERCodec", "BERCodec", "PERCodec",

    # Constants
    "ENCODE_OK", "DECODE_OK", "ERROR_INSUFFICIENT_DATA",
    "ERROR_INVALID_VALUE", "ERROR_CONSTRAINT_VIOLATION",
]