# Constants to match C and Scala implementations
OBJECT_IDENTIFIER_MAX_LENGTH = 20

# Bit manipulation constants
NO_OF_BITS_IN_BYTE = 8
NO_OF_BITS_IN_WORD = 16
NO_OF_BITS_IN_DWORD = 32
NO_OF_BITS_IN_SHORT = 16
NO_OF_BITS_IN_INT = 32
NO_OF_BITS_IN_LONG = 64

# Error codes to match C implementation
ERR_INSUFFICIENT_DATA = 101
ERR_INCORRECT_PER_STREAM = 102
ERR_INVALID_CHOICE_ALTERNATIVE = 103
ERR_INVALID_ENUM_VALUE = 104
ERR_INVALID_XML_FILE = 200
ERR_INVALID_BER_FILE = 201
ERR_BER_LENGTH_MISMATCH = 202

# Error codes from Scala implementation
NOT_INITIALIZED_ERR_CODE = 1337
ERR_INVALID_ENUM_VALUE_SCALA = 2805
FAILED_READ_ERR_CODE = 5400